version: '3.7'
services:
  haproxy:
    image: nickadam/haproxy-env:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 8081
        published: 8081
        protocol: tcp
    environment:
      HAPROXY_CONFIG: |
        global
          user root
          group root

        defaults
          log     global
          mode    tcp
          timeout connect 10s
          timeout client 1d
          timeout server 1d
          timeout tunnel 1d
          timeout client-fin 10s
          timeout server-fin 10s

        listen google
          bind :8080
          server google www.google.com:80

        listen bing
          bind :8081
          server bing www.bing.com:80
